# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-17 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_remove_carrito_compra_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_compra',
            name='id',
        ),
        migrations.AlterField(
            model_name='carrito_compra',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
