# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_corto', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('resumen', models.TextField(max_length=250, null=True)),
                ('portada', models.ImageField(null=True, upload_to='baners_cursos')),
                ('duracion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('es_gratis', models.BooleanField(default=False)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('categorias', models.ManyToManyField(to='cursos.Categoria')),
            ],
        ),
    ]
